import { readFileSync } from 'node:fs';
import { init, Wallet } from './bee_sdk.mjs';
const ENDPOINTS = ["https://mainnet.ackinacki.org"];
const BACKEND   = "https://app-backend.ackinacki.org/api/";
const APP_ID    = "0x" + "0".repeat(63) + "2";
const NAME = process.argv[2] || "yasan1";
await init({ module_or_path: readFileSync(new URL('./bee_sdk_bg.wasm', import.meta.url)) });
console.log("[ok] wasm instantiated");
const w = new Wallet(ENDPOINTS, null, BACKEND, APP_ID);
console.log("[ok] Wallet constructed");
const av = await w.check_name_availability(NAME);
const mfa = av.multifactor_address;
console.log("[ok] multifactor_address:", mfa);
const bal = await w.get_multifactor_balances({ multifactor_address: mfa });
const pg = bal.popitgame, ecc = bal.ecc;
console.log("[ok] ecc:", typeof ecc, JSON.stringify(ecc));
console.log("[ok] popitgame:", typeof pg, JSON.stringify(pg));
const locked = pg && pg["1"] ? Number(pg["1"])/1e9 : null;
console.log("[ok] LOCKED REWARD (NACKL):", locked);
